name: Build & Test

on:
  push:
    branches: [ "main", "versions-and-release" ]
  pull_request:
    branches: [ "main", "versions-and-release" ]

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3   

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
  
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-go-installation: true

    - name: Test
      run: go test -v ./...
